%YAML 1.2
---
name: kb1-256x20
gpu: 0
dataset:
  num_chunks: 16865
  train_ratio: 0.95
  input_train: /content/gdrive/My Drive/Chess/Engines/LC0/Training 4/Training Data/*/
  input_test: /content/gdrive/My Drive/Chess/Engines/LC0/Training 4/Training Data/*/
training:
  batch_size: 512
  test_steps: 2000
  train_avg_report_steps: 1
  total_steps: 100000
  checkpoint_steps: 1000
  warmup_steps: 250
  shuffle_size: 524288
  lr_values:
    - 0.02
    - 0.002
    - 0.0005
  lr_boundaries:
    - 100000
    - 130000
  policy_loss_weight: 1
  value_loss_weight: 1
  moves_left_loss_weight: .01
  path: /content/gdrive/My Drive/Chess/Engines/LC0/Produced Networks/Training 4/
model:
  filters: 256
  residual_blocks: 20
  se_ratio: 8
...
